### ISSUE TITLE
Pre-flight test launch

### ISSUE THREAD

**Issue by jimcadden** [IBM/autopilot#1]
We need the ability to automatically launch a configurable set of test before the job starts. This could happen through an  admission webhook, with object labels, or manually via an or API call or future dashboard (#2) . The job should not begin if the pre-flight test has failures.  

Pre-flight test can include
- PCI-link 
- #3
-  `dcgmi –r 3`

**Comment by cmisale** [comment]
Currently working on launching dcgmi r 3 as external job.
It is used as periodic, invasive check but can be reused in the pre flight checks

**Comment by cmisale** [comment]
PR available [https://github.com/IBM/autopilot/pull/8](https://github.com/IBM/autopilot/pull/8)

**Comment by cmisale** [comment]
Stale issue. Will reopen if needed.
