### ISSUE TITLE
Is the `all` target in `runAllTestsLocal` accurate and/or necessary? 

### ISSUE THREAD

**Issue by jimcadden** [IBM/autopilot#11]
I noticed the `all` target in the switch statement of `runAllTestsLocal` does not execute `runGPUMem` Is this missing or is an intentional omission?

Code-wise, the `all` target duplicates a decent amount of code that I would like to clean up. 

- Can we remove `all` as an option and require the list to be explicit? 
or
- Can we make `all` run all tests incl. `runGPUMem`? 

https://github.com/IBM/autopilot/blob/65b9f4ebb7ba4e831461badbcb576f82f42e5751/autopilot-daemon/pkg/handlers/healthchecks.go#L88

**Comment by cmisale** [comment]
gpumem is not part of periodic checks, the runall is for periodic ones basically.
That's a more intrusive test and we want to run it on demand

**Comment by jimcadden** [comment]
Makes sense. Ok, so maybe we remove `runGPUMem` from that switch statement altogether and make it a stand-alone call? It seems like we're doing a little too much in that function and when the list is configurable it could get messy. 

I'll push a patch to a branch and let me know what you think

**Comment by cmisale** [comment]
I am already working on that file, I did a test refactor of that function but not pushed yet. 
Let me finish with that, since I've started already.. thanks for taking a look tho
