### ISSUE TITLE
Node labels

### ISSUE THREAD

**Issue by jimcadden** [IBM/autopilot#4]
Add the ability for autopilot to add/remove labels on its node based on the results of tests.

e.g., `autopilot-node-status=healthy`, `autopilot-node-status=unhealthy`   `autopilot-node-status=unknown`

- Introduce the k8s `client-go` library to interact with node labels 
https://github.com/kubernetes/client-go/tree/v0.29.2/examples

- You likely will need to extend the helm rules to allow node modifications: https://github.com/IBM/autopilot/blob/65b9f4ebb7ba4e831461badbcb576f82f42e5751/autopilot-daemon/helm-charts/autopilot/templates/serviceaccount.yaml#L33  

## internal methods  (brainstorming) 
The below assume a single autopilot label per node
```
type label_num int

labelMap := map[label_num] string{
   0: "healthy"
   1: "unhealthy"
   2: "unknown"
   ... // more? 
}

func AddLabel(label_num) 
func ClearLabel() 
func GetLabel() label_num 
func printLabel(label_num) string
```

**Comment by jimcadden** [comment]
**Q**: Should we limit it to one autopilot label per node? 

# internal methods 
```
type label_num int

func add_label(address, label_num) // add or overwrite? 
func clear_label(address, label_num) 
func clear_all_labels(address)
func get_label(address) label_num 
```
## API 
```
GetLabel() string 
```

**Comment by jimcadden** [comment]
label appended with a timestamp?

**Comment by lasch** [comment]
Add another label e.g. `test_active` that indicates a currently running test?
On top of that: if a distinction is needed between 'node is to be scheduled for a test' and 'node is actively running a test', then maybe yet another label could be useful (e.g. `test_requested`)

**Comment by cmisale** [comment]
Addressed by 
https://github.com/IBM/autopilot/pull/8
https://github.com/IBM/autopilot/pull/18
https://github.com/IBM/autopilot/pull/19

We can close this issue
