### ISSUE TITLE
[Bug] Error in Step 2 of Install section in README

### ISSUE THREAD

**Issue by Anish701** [IBM/autopilot#49]
# Summary

Step 2 of the Install section on the README instructs users to use the following command to install Autopilot:
`helm upgrade autopilot autopilot/autopilot-daemon --install --namespace=<default> -f your-config.yml`
However, this command is outdated as the helm chart name is autopilot, not autopilot-daemon. The correct command should be:
`helm upgrade autopilot autopilot/autopilot --install --namespace=<default> -f your-config.yml`

## Steps To Reproduce

Follow Step 1 of the Install section on the README, then execute the command listed in Step 2.

## Evidence

![image](https://github.com/user-attachments/assets/15c16398-07f3-4de6-9643-64f4ccfb9f6b)

## Proposed Solution

The command in Step 2 of the Install section of the README should be changed to:
`helm upgrade autopilot autopilot/autopilot --install --namespace=<default> -f your-config.yml`

**Comment by Vezio** [comment]
Closing. Fixed in this [PR](https://github.com/IBM/autopilot/pull/50). Thanks @Anish701 !
