### ISSUE TITLE
CPU & GPU data columns in the Prometheus 

### ISSUE THREAD

**Issue by jimcadden** [IBM/autopilot#7]
Cpu model and GPU model data points in needed prometheus outputs 

 `autopilot-daemon/pkg/util/global.go:L22`

Expand the `HchecksGauge` with `cpu` and `gpu` columns 

Pull the CPU and GPU values from `os.Getenv` ??

**Comment by remolina** [comment]
Here are some of the metadata.labels in the node specs I found for cpu/gpu info

CPU:
```
    feature.node.kubernetes.io/cpu-model.family: "6"
    feature.node.kubernetes.io/cpu-model.id: "143"
    feature.node.kubernetes.io/cpu-model.vendor_id: Intel
```

GPU:
```
            "nvidia.com/cuda.driver.major": "535",
            "nvidia.com/cuda.driver.minor": "104",
            "nvidia.com/cuda.driver.rev": "05",
            "nvidia.com/cuda.runtime.major": "12",
            "nvidia.com/cuda.runtime.minor": "2",
            "nvidia.com/gfd.timestamp": "1708397918",
            "nvidia.com/gpu-driver-upgrade-state": "upgrade-done",
            "nvidia.com/gpu.compute.major": "9",
            "nvidia.com/gpu.compute.minor": "0",
            "nvidia.com/gpu.count": "8",
            "nvidia.com/gpu.deploy.container-toolkit": "true",
            "nvidia.com/gpu.deploy.dcgm": "true",
            "nvidia.com/gpu.deploy.dcgm-exporter": "true",
            "nvidia.com/gpu.deploy.device-plugin": "true",
            "nvidia.com/gpu.deploy.driver": "true",
            "nvidia.com/gpu.deploy.gpu-feature-discovery": "true",
            "nvidia.com/gpu.deploy.mig-manager": "true",
            "nvidia.com/gpu.deploy.node-status-exporter": "true",
            "nvidia.com/gpu.deploy.nvsm": "",
            "nvidia.com/gpu.deploy.operator-validator": "true",
            "nvidia.com/gpu.family": "hopper",
            "nvidia.com/gpu.machine": "SYS-821GE-TNHR",
            "nvidia.com/gpu.memory": "81559",
            "nvidia.com/gpu.present": "true",
            "nvidia.com/gpu.product": "NVIDIA-H100-80GB-HBM3",
            "nvidia.com/gpu.replicas": "1",
            "nvidia.com/mig.capable": "true",
            "nvidia.com/mig.strategy": "single",
```

Are any of these what we are looking for with this issue by chance? If any of these work, we can pull these values similar to how the node name is pulled via os.Getenv.

Would also need to figure out if the labels change with different gpu models as that would impact this design thought.

**Comment by jimcadden** [comment]
`nvidia.com/gpu.product` tells us everything we need to know about the GPU. 

For CPU, the `vendor` + `family` + `id` combined does the trick. For example, [Sapphire Rapids is "Intel Family 6 Model 143" ](https://en.wikichip.org/wiki/intel/microarchitectures/sapphire_rapids)

**Comment by remolina** [comment]
Was able to pull CPU data from my local machine using cpuid go library. This is more data than is needed for this particular issue, but wanted to confirm it worked and which variables we would be interested in.

```
$ go run cpuData.go 
Name: Apple M1 Max
PhysicalCores: 10
ThreadsPerCore: 1
LogicalCores: 10
Family 458787763 Model: 0 Vendor ID: VendorUnknown
Features: AESARM,ASIMD,ASIMDDP,ASIMDHP,ASIMDRDM,ATOMICS,CRC32,DCPOP,FCMA,FP,FPHP,GPA,JSCVT,LRCPC,PMULL,SHA1,SHA2,SHA3,SHA512
Cacheline bytes: 128
L1 Data Cache: 65536 bytes
L1 Instruction Cache: 131072 bytes
L2 Cache: 4194304 bytes
L3 Cache: -1 bytes
Frequency 0 hz
```

Looking into `nvidia-smi --query-gpu=gpu_name` to pull the gpu info now

**Comment by jimcadden** [comment]
Vendor ID, Family, Model, in that order

**Comment by cmisale** [comment]
Family and Model are numbers, I doubt it's easy to remember all that stuff.
If we can get something similar to 
```
"nvidia.com/gpu.product": "NVIDIA-H100-80GB-HBM3",
```
for cpu, that would be great.

**Comment by jimcadden** [comment]
https://pkg.go.dev/github.com/mohae/joefriday/cpu/cpuinfo has a field for "Model Name", which isn't provided by CPUid. Worth looking into what that displays on x86.

@cmisale are you thinking something with the codename, like "Intel Sapphire Rapids Family 6 Model 143" or just "Intel Sapphire Rapids"  ?

**Comment by cmisale** [comment]
I think it's sufficient just "Intel Sapphire Rapids". We can always expand that in the future if we receive request for that

**Comment by jimcadden** [comment]
@remolina please try the cpuinfo package on the jump-host and see what we get for Model Name. Or, better yet, a container on the cluster. We want to see something like Xeon or Sapphire Rapids. 

@cmisale I'm not sure the Intel project codename is ever returned from these interfaces, but we can always add a switch statement to replace "Family 6 Model 143" with "Sapphire Rapids" for the few other cpu types we support in Vela (I know this is a crap solution lol)

**Comment by cmisale** [comment]
@jimcadden ah that's not great that the code name is never returned.. then fine let's get creative..

**Comment by jimcadden** [comment]
The code name may be returned from cpunfo. We'll see what @remolina finds out

**Comment by remolina** [comment]
```
processor	: 31
vendor_id	: GenuineIntel
cpu family	: 6
model		: 143
model name	: Intel(R) Xeon(R) Gold 6426Y
```

Manually confirmed from a docker container on the jumphost that the model name from the cpuinfo package is the parameter we need.  Working on integrating the package into a go script. the documentation isn't too intuitive so it's been taking some time to try and integrate it properly.

**Comment by cmisale** [comment]
That's great!!

**Comment by minghungchen** [comment]
Other than using the cpuinfo go package, I think you can parse `/proc/cpuinfo` directly without adding a new dependancy.
You can retrieve the cpu model in /proc/cpuinfo simply with the first line starting with "model name".

On two of the VM-based nodes, this is what I see:
`model name      : Intel Xeon Processor (Icelake)`
`model name      : Intel Xeon Processor (Cascadelake)`
I think this should be good enough for the use cases with VMs

However, please note you may get something else on BM-based nodes such as
`model name	: Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz`
`model name	: Intel(R) Xeon(R) Platinum 8474C`
`model name	: AMD EPYC 7742 64-Core Processor`
You may want to process the string to remove the part after `@` to only keep the actual model name, and I highly suspect the cpuinfo go package probably has the same behavior.

Also note that if you need the code name of CPU for this kind of BM cases, you may need to build a vendor id, cpu family, model, and code name mapping table using the data from Intel and AMD.

**Comment by remolina** [comment]
resolved by https://github.com/IBM/autopilot/pull/22
